# Generated by Django 5.2.10 on 2026-01-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carpets/', verbose_name='Путь к файлу')),
                ('design', models.CharField(max_length=50, verbose_name='Рисунок')),
                ('color', models.CharField(max_length=50, verbose_name='Колорит')),
                ('palette', models.CharField(max_length=50, verbose_name='Палитра')),
                ('size', models.CharField(max_length=50, verbose_name='Размеры')),
                ('extra', models.CharField(blank=True, max_length=50, null=True, verbose_name='Доп. параметр')),
            ],
        ),
    ]
