# Generated by Django 5.2.10 on 2026-01-31 08:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц')),
                ('land_tax', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Земельный налог')),
                ('rent_payment', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Пользование жилым пом.')),
                ('capital_repair', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Кап. ремонт')),
                ('maintenance', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Тех. обслуживание')),
                ('heating', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Отопление')),
                ('water_sewage', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Вода и канализация')),
                ('water_heating', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Подогрев воды')),
                ('electricity', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Электроэнергия')),
                ('elevator_maintenance', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='ТО лифта')),
                ('elevator_electricity', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Эл-энергия лифта')),
                ('waste_management', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='ТКО')),
                ('dog_tax', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Содержание собак')),
                ('common_lighting', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Освещение вспом. пом.')),
                ('common_sanitation', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Сан. содерж. вспом. пом.')),
                ('recalculation', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Перерасчет')),
            ],
            options={
                'verbose_name': 'Ежемесячный платеж',
                'verbose_name_plural': 'Ежемесячные платежи',
            },
        ),
        migrations.CreateModel(
            name='ResidentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО жильца')),
                ('account_number', models.CharField(max_length=50, verbose_name='Лицевой счет')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Год')),
                ('room_number', models.CharField(max_length=10, verbose_name='Номер комнаты')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Общая площадь')),
                ('living_area', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Жилая площадь')),
                ('family_count', models.PositiveIntegerField(default=1, verbose_name='Состав семьи')),
                ('dog_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во собак')),
            ],
            options={
                'verbose_name': 'Карточка жильца (год)',
                'verbose_name_plural': 'Карточки жильцов',
                'unique_together': {('account_number', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='Resident',
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dormitory.residentcard'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlypayment',
            unique_together={('card', 'month')},
        ),
    ]
