# Generated by Django 5.2.10 on 2026-02-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_monthlypayment_residentcard_delete_resident_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True, verbose_name='Техническое название услуги')),
                ('label', models.CharField(max_length=255, verbose_name='Отображаемое название')),
                ('value', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Значение тарифа')),
                ('unit', models.CharField(max_length=50, verbose_name='Ед. изм.')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
