# Generated by Django 5.2.10 on 2026-01-31 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='checkpoint/docs/', verbose_name='Документ (PDF)')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='checkpoint/photos/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=20, verbose_name='Гос. номер')),
                ('car_brand', models.CharField(max_length=50, verbose_name='Марка машины')),
                ('driver_name', models.CharField(max_length=255, verbose_name='ФИО водителя')),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Организация')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время въезда')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Время выезда')),
            ],
            options={
                'verbose_name': 'Запись КПП',
                'verbose_name_plural': 'Журнал КПП',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.DeleteModel(
            name='VehiclePass',
        ),
        migrations.AddField(
            model_name='vehiclephoto',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='checkpoint.vehiclerecord'),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='checkpoint.vehiclerecord'),
        ),
    ]
